---
# tasks file for .

- name: Update repositories cache and install "mariadb-server" package
  apt:
    name: mariadb-server
    update_cache: yes

- name: Copy config file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  register: reload_mariadb

- name: Enable and start 
  systemd:
    state: reloaded
    enabled: True
    name: mysql
  when: ansible_service_mgr == "systemd" and reload_mariadb.changed
