---
# main tasks file for mariadb
- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false
    
- name: Install "mariadb-server" package
  apt:
    name: mariadb-server

- name: Copy config file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  register: reload_mariadb

- name: Enable and start 
  systemd:
    state: reloaded
    enabled: True
    name: mysql
  when: ansible_service_mgr == "systemd" and reload_mariadb.changed
