---
- name: Install mariadb-server and python-mysqldb packages
  apt:
    name:
      - mariadb-server
      - python-mysqldb
      - python3-mysqldb

- name: Copy config file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  register: reload_mariadb

- name: Enable and start mysql service
  systemd:
    state: restarted
    enabled: True
    name: mysql
  when: ansible_service_mgr == "systemd" and reload_mariadb.changed

- name: Ensure configured databases exist
  mysql_db:
    name: "{{ item }}"
  with_items: "{{ mariadb_ensure_databases }}"

- name: Ensure configured users exist
  mysql_user:
    name: "{{ item.key }}"
    password: "{{ item.value['password'] | default(omit) }}"
    priv: "{{ item.value['privileges'] | default(omit) }}"
  no_log: True
  loop: "{{ mariadb_ensure_users |dict2items }}"
